{% set name = "ANTs" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v{{ version }}.tar.gz
  sha256: 8e3a7c0d3dab05883cba466aff262d78d832f679491318b94ce49b606565cebe

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel
  run:
    - libitk

test:
  commands:
    - antsRegistration --help

about:
  home: https://stnava.github.io/ANTs/
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  doc_url: http://stnava.github.io/ANTsDoc
  dev_url: https://github.com/ANTsX/ANTs/wiki

extra:
  recipe-maintainers:
    - ghisvail
