{% set name = "ANTs" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v{{ version }}.tar.gz
  sha256: 6fb294e1c7edb238aa05b23b8bd9a9ca1e3e8bf5554f7839c70abb58e1f867df

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel
  run:
    - {{ pin_compatible('libitk', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - antsRegistration --help

about:
  home: https://stnava.github.io/ANTs/
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  doc_url: http://stnava.github.io/ANTsDoc
  dev_url: https://github.com/ANTsX/ANTs/wiki

extra:
  recipe-maintainers:
    - ghisvail
