{% set name = "ANTs" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v{{ version }}.tar.gz
  sha256: b38bc5438a7bef0c460dc7014320fee58dd1439e2397876645ad9269f52d9451

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel
  run:
    - {{ pin_compatible('libitk', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - antsRegistration --help

about:
  home: https://stnava.github.io/ANTs/
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  doc_url: http://stnava.github.io/ANTsDoc
  dev_url: https://github.com/ANTsX/ANTs/wiki

extra:
  recipe-maintainers:
    - ghisvail
